import { RecipeTemplate } from './recipe-templates';

// Collection of diverse recipe templates
export const recipeTemplates: RecipeTemplate[] = [
  // Breakfast Recipes
  {
    id: 'demo-recipe-1',
    title: 'Classic Pancakes',
    description: 'Fluffy buttermilk pancakes perfect for weekend mornings.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
    difficulty: 'easy',
    cuisine: 'american',
    mealType: ['breakfast'],
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 4,
    servingsNotes: 'Makes about 8 pancakes',
    ingredients: [
      { name: 'All-purpose Flour', amount: 2, unit: 'cups', category: 'grains' },
      { name: 'Sugar', amount: 2, unit: 'tbsp', category: 'sweeteners' },
      { name: 'Baking Powder', amount: 2, unit: 'tsp', category: 'baking' },
      { name: 'Salt', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Milk', amount: 1.75, unit: 'cups', category: 'dairy' },
      { name: 'Eggs', amount: 2, unit: 'pieces', category: 'dairy' },
      { name: 'Butter', amount: 4, unit: 'tbsp', notes: 'melted', category: 'dairy' }
    ],
    instructions: [
      { step: 1, instruction: 'In a bowl, whisk together flour, sugar, baking powder, and salt.' },
      { step: 2, instruction: 'In another bowl, combine milk, eggs, and melted butter.' },
      { step: 3, instruction: 'Pour wet ingredients into dry ingredients and mix until just combined.' },
      { step: 4, instruction: 'Heat griddle or pan over medium heat. Pour 1/4 cup batter per pancake.', temperature: 350 },
      { step: 5, instruction: 'Cook until bubbles form on surface, then flip and cook until golden.', timer: 3 }
    ],
    nutrition: { calories: 320, protein: 12, carbs: 45, fat: 12, fiber: 2, sugar: 8, sodium: 600 },
    tags: ['breakfast', 'comfort-food', 'kid-friendly'],
    dietary: ['vegetarian'],
    ratings: { average: 4.7, count: 23 },
    isFavorite: true,
    cookCount: 8,
    lastCookedDays: 5,
    createdDays: 45
  },

  {
    id: 'demo-recipe-2',
    title: 'Avocado Toast with Poached Egg',
    description: 'Creamy avocado on sourdough topped with a perfectly poached egg.',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
    difficulty: 'medium',
    cuisine: 'modern',
    mealType: ['breakfast', 'brunch'],
    prepTime: 10,
    cookTime: 8,
    totalTime: 18,
    servings: 2,
    servingsNotes: 'Serves 2 people',
    ingredients: [
      { name: 'Sourdough Bread', amount: 4, unit: 'slices', category: 'grains' },
      { name: 'Avocado', amount: 2, unit: 'pieces', notes: 'ripe', category: 'fruits' },
      { name: 'Eggs', amount: 2, unit: 'pieces', notes: 'fresh', category: 'dairy' },
      { name: 'Lemon Juice', amount: 1, unit: 'tbsp', category: 'condiments' },
      { name: 'Salt', amount: 0.5, unit: 'tsp', category: 'spices' },
      { name: 'Black Pepper', amount: 0.25, unit: 'tsp', notes: 'freshly ground', category: 'spices' },
      { name: 'Red Pepper Flakes', amount: 0.25, unit: 'tsp', isOptional: true, category: 'spices' }
    ],
    instructions: [
      { step: 1, instruction: 'Toast bread slices until golden brown.', timer: 3 },
      { step: 2, instruction: 'Bring water to simmer in a saucepan. Add splash of vinegar.' },
      { step: 3, instruction: 'Crack eggs into small bowls. Create whirlpool in water and gently add eggs.', timer: 3 },
      { step: 4, instruction: 'Cook eggs for 3-4 minutes for runny yolks.', timer: 4 },
      { step: 5, instruction: 'Mash avocado with lemon juice, salt, and pepper. Spread on toast.' },
      { step: 6, instruction: 'Top with poached eggs and season with pepper flakes.' }
    ],
    nutrition: { calories: 285, protein: 14, carbs: 24, fat: 18, fiber: 8, sugar: 3, sodium: 420 },
    tags: ['healthy', 'trendy', 'protein-rich'],
    dietary: ['vegetarian', 'gluten-free-option'],
    ratings: { average: 4.4, count: 19 },
    cookCount: 3,
    lastCookedDays: 12,
    createdDays: 60
  },

  // Lunch Recipes
  {
    id: 'demo-recipe-3',
    title: 'Mediterranean Quinoa Bowl',
    description: 'Healthy quinoa bowl with fresh vegetables, feta, and lemon dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    difficulty: 'easy',
    cuisine: 'mediterranean',
    mealType: ['lunch', 'dinner'],
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    servingsNotes: 'Serves 4 as main dish',
    ingredients: [
      { name: 'Quinoa', amount: 1.5, unit: 'cups', category: 'grains' },
      { name: 'Cucumber', amount: 1, unit: 'piece', notes: 'diced', category: 'vegetables' },
      { name: 'Cherry Tomatoes', amount: 2, unit: 'cups', notes: 'halved', category: 'vegetables' },
      { name: 'Red Onion', amount: 0.5, unit: 'piece', notes: 'thinly sliced', category: 'vegetables' },
      { name: 'Feta Cheese', amount: 1, unit: 'cup', notes: 'crumbled', category: 'dairy' },
      { name: 'Kalamata Olives', amount: 0.5, unit: 'cup', category: 'vegetables' },
      { name: 'Olive Oil', amount: 0.25, unit: 'cup', category: 'oils' },
      { name: 'Lemon Juice', amount: 3, unit: 'tbsp', category: 'condiments' },
      { name: 'Fresh Herbs', amount: 0.25, unit: 'cup', notes: 'parsley or mint', category: 'herbs' }
    ],
    instructions: [
      { step: 1, instruction: 'Cook quinoa according to package directions. Let cool.', timer: 20 },
      { step: 2, instruction: 'Dice cucumber and halve cherry tomatoes.' },
      { step: 3, instruction: 'Thinly slice red onion and soak in cold water for 10 minutes.' },
      { step: 4, instruction: 'Whisk together olive oil, lemon juice, salt, and pepper.' },
      { step: 5, instruction: 'Combine quinoa, vegetables, feta, and olives in large bowl.' },
      { step: 6, instruction: 'Toss with dressing and fresh herbs before serving.' }
    ],
    nutrition: { calories: 380, protein: 15, carbs: 42, fat: 18, fiber: 6, sugar: 8, sodium: 520 },
    tags: ['healthy', 'mediterranean', 'meal-prep'],
    dietary: ['vegetarian', 'gluten-free'],
    ratings: { average: 4.6, count: 31 },
    isFavorite: true,
    cookCount: 12,
    lastCookedDays: 3,
    createdDays: 20
  },

  {
    id: 'demo-recipe-4',
    title: 'Asian Chicken Lettuce Wraps',
    description: 'Light and flavorful chicken lettuce wraps with Asian-inspired sauce.',
    image: 'https://images.unsplash.com/photo-1565299585323-38174c5e48eb?w=400',
    difficulty: 'easy',
    cuisine: 'asian',
    mealType: ['lunch', 'dinner'],
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    servings: 4,
    servingsNotes: 'Serves 4 as appetizer or light meal',
    ingredients: [
      { name: 'Ground Chicken', amount: 1, unit: 'lb', category: 'protein' },
      { name: 'Butter Lettuce', amount: 1, unit: 'head', notes: 'leaves separated', category: 'vegetables' },
      { name: 'Water Chestnuts', amount: 1, unit: 'can', notes: 'diced', category: 'vegetables' },
      { name: 'Green Onions', amount: 4, unit: 'pieces', notes: 'chopped', category: 'vegetables' },
      { name: 'Soy Sauce', amount: 3, unit: 'tbsp', category: 'condiments' },
      { name: 'Sesame Oil', amount: 2, unit: 'tsp', category: 'oils' },
      { name: 'Rice Vinegar', amount: 1, unit: 'tbsp', category: 'condiments' },
      { name: 'Ginger', amount: 1, unit: 'tbsp', notes: 'minced', category: 'spices' },
      { name: 'Garlic', amount: 3, unit: 'cloves', notes: 'minced', category: 'vegetables' }
    ],
    instructions: [
      { step: 1, instruction: 'Heat oil in large skillet over medium-high heat.' },
      { step: 2, instruction: 'Add ground chicken and cook, breaking up, until browned.', timer: 6 },
      { step: 3, instruction: 'Add garlic and ginger, cook until fragrant.', timer: 1 },
      { step: 4, instruction: 'Stir in soy sauce, sesame oil, and rice vinegar.' },
      { step: 5, instruction: 'Add water chestnuts and green onions, cook 2 minutes.', timer: 2 },
      { step: 6, instruction: 'Serve chicken mixture in lettuce cups.' }
    ],
    nutrition: { calories: 220, protein: 24, carbs: 8, fat: 10, fiber: 2, sugar: 4, sodium: 680 },
    tags: ['healthy', 'low-carb', 'asian-inspired'],
    dietary: ['gluten-free-option', 'dairy-free'],
    ratings: { average: 4.5, count: 27 },
    cookCount: 6,
    lastCookedDays: 18,
    createdDays: 35
  },

  // Dinner Recipes
  {
    id: 'demo-recipe-5',
    title: 'Honey Garlic Salmon',
    description: 'Pan-seared salmon with a sweet and savory honey garlic glaze.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    difficulty: 'medium',
    cuisine: 'modern',
    mealType: ['dinner'],
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 4,
    servingsNotes: 'Serves 4 people',
    ingredients: [
      { name: 'Salmon Fillets', amount: 4, unit: 'pieces', notes: '6 oz each', category: 'protein' },
      { name: 'Honey', amount: 0.25, unit: 'cup', category: 'sweeteners' },
      { name: 'Soy Sauce', amount: 3, unit: 'tbsp', category: 'condiments' },
      { name: 'Garlic', amount: 4, unit: 'cloves', notes: 'minced', category: 'vegetables' },
      { name: 'Ginger', amount: 1, unit: 'tsp', notes: 'minced', category: 'spices' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp', category: 'oils' },
      { name: 'Lemon', amount: 1, unit: 'piece', notes: 'juiced', category: 'fruits' },
      { name: 'Green Onions', amount: 2, unit: 'pieces', notes: 'chopped', isOptional: true, category: 'vegetables' }
    ],
    instructions: [
      { step: 1, instruction: 'Pat salmon dry and season with salt and pepper.' },
      { step: 2, instruction: 'Heat olive oil in large skillet over medium-high heat.' },
      { step: 3, instruction: 'Cook salmon skin-side up for 4-5 minutes until golden.', timer: 5 },
      { step: 4, instruction: 'Flip salmon and cook 3-4 minutes more.', timer: 4 },
      { step: 5, instruction: 'Remove salmon. Add garlic, ginger to pan, cook 30 seconds.', timer: 1 },
      { step: 6, instruction: 'Add honey, soy sauce, lemon juice. Simmer until thickened.', timer: 2 },
      { step: 7, instruction: 'Return salmon to pan, spoon glaze over fish.' }
    ],
    nutrition: { calories: 380, protein: 35, carbs: 18, fat: 18, fiber: 0, sugar: 16, sodium: 720 },
    tags: ['healthy', 'quick', 'protein-rich'],
    dietary: ['gluten-free-option', 'dairy-free'],
    ratings: { average: 4.8, count: 42 },
    isFavorite: true,
    cookCount: 15,
    lastCookedDays: 8,
    createdDays: 25
  },

  {
    id: 'demo-recipe-6',
    title: 'Beef and Broccoli Stir Fry',
    description: 'Classic Chinese-style beef and broccoli in savory sauce.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    difficulty: 'medium',
    cuisine: 'chinese',
    mealType: ['dinner'],
    prepTime: 20,
    cookTime: 15,
    totalTime: 35,
    servings: 4,
    servingsNotes: 'Serves 4 with rice',
    ingredients: [
      { name: 'Beef Sirloin', amount: 1, unit: 'lb', notes: 'sliced thin', category: 'protein' },
      { name: 'Broccoli', amount: 1.5, unit: 'lbs', notes: 'cut into florets', category: 'vegetables' },
      { name: 'Soy Sauce', amount: 0.25, unit: 'cup', category: 'condiments' },
      { name: 'Oyster Sauce', amount: 2, unit: 'tbsp', category: 'condiments' },
      { name: 'Cornstarch', amount: 1, unit: 'tbsp', category: 'baking' },
      { name: 'Garlic', amount: 4, unit: 'cloves', notes: 'minced', category: 'vegetables' },
      { name: 'Ginger', amount: 1, unit: 'tbsp', notes: 'minced', category: 'spices' },
      { name: 'Vegetable Oil', amount: 3, unit: 'tbsp', category: 'oils' },
      { name: 'Sesame Oil', amount: 1, unit: 'tsp', category: 'oils' }
    ],
    instructions: [
      { step: 1, instruction: 'Marinate sliced beef with 2 tbsp soy sauce and cornstarch for 15 minutes.' },
      { step: 2, instruction: 'Blanch broccoli in boiling water for 2 minutes, then drain.', timer: 2 },
      { step: 3, instruction: 'Heat 1 tbsp oil in wok over high heat.' },
      { step: 4, instruction: 'Stir-fry beef until browned, about 3-4 minutes. Remove.', timer: 4 },
      { step: 5, instruction: 'Add remaining oil, stir-fry garlic and ginger for 30 seconds.', timer: 1 },
      { step: 6, instruction: 'Add broccoli, remaining soy sauce, and oyster sauce.', timer: 2 },
      { step: 7, instruction: 'Return beef to wok, toss everything together. Drizzle with sesame oil.' }
    ],
    nutrition: { calories: 320, protein: 28, carbs: 12, fat: 18, fiber: 4, sugar: 6, sodium: 980 },
    tags: ['stir-fry', 'asian', 'quick'],
    dietary: ['dairy-free'],
    ratings: { average: 4.3, count: 38 },
    cookCount: 9,
    lastCookedDays: 14,
    createdDays: 40
  },

  {
    id: 'demo-recipe-7',
    title: 'Creamy Mushroom Risotto',
    description: 'Rich and creamy arborio rice with mixed mushrooms and parmesan.',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400',
    difficulty: 'hard',
    cuisine: 'italian',
    mealType: ['dinner'],
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 6,
    servingsNotes: 'Serves 6 as main course',
    ingredients: [
      { name: 'Arborio Rice', amount: 2, unit: 'cups', category: 'grains' },
      { name: 'Mixed Mushrooms', amount: 1, unit: 'lb', notes: 'shiitake, cremini, oyster', category: 'vegetables' },
      { name: 'Chicken Broth', amount: 6, unit: 'cups', notes: 'warm', category: 'liquids' },
      { name: 'White Wine', amount: 0.5, unit: 'cup', notes: 'dry', category: 'liquids' },
      { name: 'Onion', amount: 1, unit: 'piece', notes: 'finely chopped', category: 'vegetables' },
      { name: 'Garlic', amount: 3, unit: 'cloves', notes: 'minced', category: 'vegetables' },
      { name: 'Parmesan Cheese', amount: 1, unit: 'cup', notes: 'grated', category: 'dairy' },
      { name: 'Butter', amount: 4, unit: 'tbsp', category: 'dairy' },
      { name: 'Heavy Cream', amount: 0.25, unit: 'cup', category: 'dairy' }
    ],
    instructions: [
      { step: 1, instruction: 'Sauté mushrooms in 2 tbsp butter until golden. Set aside.', timer: 8 },
      { step: 2, instruction: 'In same pan, sauté onion until translucent.', timer: 5 },
      { step: 3, instruction: 'Add garlic and rice, stir for 2 minutes until rice is toasted.', timer: 2 },
      { step: 4, instruction: 'Add wine and stir until absorbed.', timer: 2 },
      { step: 5, instruction: 'Add warm broth one ladle at a time, stirring constantly.', timer: 25 },
      { step: 6, instruction: 'When rice is creamy and al dente, stir in mushrooms, cream, remaining butter.' },
      { step: 7, instruction: 'Remove from heat, stir in parmesan cheese. Season and serve immediately.' }
    ],
    nutrition: { calories: 420, protein: 14, carbs: 52, fat: 16, fiber: 2, sugar: 4, sodium: 680 },
    tags: ['comfort-food', 'italian', 'creamy'],
    dietary: ['vegetarian'],
    ratings: { average: 4.7, count: 29 },
    cookCount: 4,
    lastCookedDays: 22,
    createdDays: 55
  },

  // International Favorites
  {
    id: 'demo-recipe-8',
    title: 'Chicken Tikka Masala',
    description: 'Tender chicken in a rich, creamy tomato curry sauce.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
    difficulty: 'medium',
    cuisine: 'indian',
    mealType: ['dinner'],
    prepTime: 30,
    cookTime: 40,
    totalTime: 70,
    restTime: 30,
    servings: 6,
    servingsNotes: 'Serves 6 with rice and naan',
    ingredients: [
      { name: 'Chicken Thighs', amount: 2, unit: 'lbs', notes: 'boneless, cut in chunks', category: 'protein' },
      { name: 'Greek Yogurt', amount: 1, unit: 'cup', category: 'dairy' },
      { name: 'Garam Masala', amount: 2, unit: 'tsp', category: 'spices' },
      { name: 'Cumin', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Paprika', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Crushed Tomatoes', amount: 1, unit: 'can', notes: '28 oz', category: 'vegetables' },
      { name: 'Heavy Cream', amount: 1, unit: 'cup', category: 'dairy' },
      { name: 'Onion', amount: 1, unit: 'piece', notes: 'diced', category: 'vegetables' },
      { name: 'Garlic', amount: 6, unit: 'cloves', notes: 'minced', category: 'vegetables' },
      { name: 'Ginger', amount: 2, unit: 'tbsp', notes: 'minced', category: 'spices' }
    ],
    instructions: [
      { step: 1, instruction: 'Marinate chicken with yogurt, 1 tsp garam masala, cumin for 30 minutes.' },
      { step: 2, instruction: 'Cook chicken in batches until browned. Set aside.', timer: 8 },
      { step: 3, instruction: 'Sauté onion until golden, about 8 minutes.', timer: 8 },
      { step: 4, instruction: 'Add garlic, ginger, remaining spices. Cook 1 minute.', timer: 1 },
      { step: 5, instruction: 'Add crushed tomatoes, simmer 15 minutes.', timer: 15 },
      { step: 6, instruction: 'Stir in cream and chicken. Simmer 10 minutes.', timer: 10 },
      { step: 7, instruction: 'Taste and adjust seasoning. Garnish with cilantro.' }
    ],
    nutrition: { calories: 480, protein: 32, carbs: 12, fat: 34, fiber: 3, sugar: 8, sodium: 420 },
    tags: ['curry', 'indian', 'comfort-food'],
    dietary: ['gluten-free'],
    ratings: { average: 4.9, count: 56 },
    isFavorite: true,
    cookCount: 11,
    lastCookedDays: 6,
    createdDays: 15
  },

  {
    id: 'demo-recipe-9',
    title: 'Fish Tacos with Lime Crema',
    description: 'Crispy fish tacos with cabbage slaw and zesty lime crema.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
    difficulty: 'medium',
    cuisine: 'mexican',
    mealType: ['lunch', 'dinner'],
    prepTime: 25,
    cookTime: 15,
    totalTime: 40,
    servings: 4,
    servingsNotes: 'Makes 8-10 tacos',
    ingredients: [
      { name: 'White Fish Fillets', amount: 1.5, unit: 'lbs', notes: 'mahi-mahi or cod', category: 'protein' },
      { name: 'Corn Tortillas', amount: 10, unit: 'pieces', category: 'grains' },
      { name: 'Cabbage', amount: 3, unit: 'cups', notes: 'shredded', category: 'vegetables' },
      { name: 'Sour Cream', amount: 0.5, unit: 'cup', category: 'dairy' },
      { name: 'Lime', amount: 3, unit: 'pieces', notes: 'juiced and zested', category: 'fruits' },
      { name: 'Cumin', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Chili Powder', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Cilantro', amount: 0.25, unit: 'cup', notes: 'chopped', category: 'herbs' },
      { name: 'Avocado', amount: 2, unit: 'pieces', notes: 'sliced', category: 'fruits' }
    ],
    instructions: [
      { step: 1, instruction: 'Season fish with cumin, chili powder, salt, and pepper.' },
      { step: 2, instruction: 'Make lime crema: mix sour cream, lime juice, zest, and cilantro.' },
      { step: 3, instruction: 'Toss cabbage with lime juice and salt for slaw.' },
      { step: 4, instruction: 'Cook fish in hot oil until flaky and golden, 3-4 minutes per side.', timer: 8 },
      { step: 5, instruction: 'Warm tortillas in dry pan or microwave.' },
      { step: 6, instruction: 'Assemble tacos: fish, slaw, avocado, and lime crema.' }
    ],
    nutrition: { calories: 385, protein: 28, carbs: 32, fat: 18, fiber: 8, sugar: 6, sodium: 380 },
    tags: ['mexican', 'fresh', 'healthy'],
    dietary: ['gluten-free', 'pescatarian'],
    ratings: { average: 4.5, count: 33 },
    cookCount: 7,
    lastCookedDays: 11,
    createdDays: 28
  },

  // Comfort Foods
  {
    id: 'demo-recipe-10',
    title: 'Classic Mac and Cheese',
    description: 'Creamy, indulgent mac and cheese with a golden breadcrumb topping.',
    image: 'https://images.unsplash.com/photo-1543826173-1ad05b68b9d0?w=400',
    difficulty: 'easy',
    cuisine: 'american',
    mealType: ['lunch', 'dinner'],
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 8,
    servingsNotes: 'Serves 8 as side dish',
    ingredients: [
      { name: 'Elbow Pasta', amount: 1, unit: 'lb', category: 'grains' },
      { name: 'Cheddar Cheese', amount: 4, unit: 'cups', notes: 'sharp, shredded', category: 'dairy' },
      { name: 'Gruyere Cheese', amount: 1, unit: 'cup', notes: 'shredded', category: 'dairy' },
      { name: 'Milk', amount: 3, unit: 'cups', notes: 'whole milk', category: 'dairy' },
      { name: 'Butter', amount: 4, unit: 'tbsp', category: 'dairy' },
      { name: 'Flour', amount: 4, unit: 'tbsp', category: 'grains' },
      { name: 'Breadcrumbs', amount: 1, unit: 'cup', notes: 'panko', category: 'grains' },
      { name: 'Nutmeg', amount: 0.25, unit: 'tsp', category: 'spices' }
    ],
    instructions: [
      { step: 1, instruction: 'Cook pasta according to package directions. Drain and set aside.', timer: 8 },
      { step: 2, instruction: 'Melt butter in large saucepan. Whisk in flour, cook 1 minute.', timer: 1 },
      { step: 3, instruction: 'Gradually add milk, whisking constantly. Cook until thickened.', timer: 5 },
      { step: 4, instruction: 'Remove from heat, stir in cheeses until melted.' },
      { step: 5, instruction: 'Season with salt, pepper, and nutmeg. Stir in pasta.' },
      { step: 6, instruction: 'Transfer to baking dish, top with breadcrumbs.', temperature: 375 },
      { step: 7, instruction: 'Bake until bubbly and golden, about 20 minutes.', timer: 20 }
    ],
    nutrition: { calories: 520, protein: 22, carbs: 48, fat: 26, fiber: 2, sugar: 8, sodium: 680 },
    tags: ['comfort-food', 'kid-friendly', 'cheesy'],
    dietary: ['vegetarian'],
    ratings: { average: 4.8, count: 67 },
    isFavorite: true,
    cookCount: 21,
    lastCookedDays: 2,
    createdDays: 10
  },

  // Healthy Options
  {
    id: 'demo-recipe-11',
    title: 'Buddha Bowl with Tahini Dressing',
    description: 'Nutritious bowl with roasted vegetables, quinoa, and creamy tahini dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    difficulty: 'easy',
    cuisine: 'healthy',
    mealType: ['lunch', 'dinner'],
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 4,
    servingsNotes: 'Serves 4 as main dish',
    ingredients: [
      { name: 'Quinoa', amount: 1, unit: 'cup', category: 'grains' },
      { name: 'Sweet Potato', amount: 2, unit: 'pieces', notes: 'cubed', category: 'vegetables' },
      { name: 'Brussels Sprouts', amount: 1, unit: 'lb', notes: 'halved', category: 'vegetables' },
      { name: 'Chickpeas', amount: 1, unit: 'can', notes: 'drained and rinsed', category: 'protein' },
      { name: 'Tahini', amount: 0.25, unit: 'cup', category: 'condiments' },
      { name: 'Lemon Juice', amount: 3, unit: 'tbsp', category: 'condiments' },
      { name: 'Maple Syrup', amount: 1, unit: 'tbsp', category: 'sweeteners' },
      { name: 'Olive Oil', amount: 3, unit: 'tbsp', category: 'oils' },
      { name: 'Pumpkin Seeds', amount: 0.25, unit: 'cup', isOptional: true, category: 'nuts' }
    ],
    instructions: [
      { step: 1, instruction: 'Cook quinoa according to package directions.', timer: 15 },
      { step: 2, instruction: 'Toss sweet potato and Brussels sprouts with oil, salt, and pepper.' },
      { step: 3, instruction: 'Roast vegetables at 425°F for 20-25 minutes.', timer: 25, temperature: 425 },
      { step: 4, instruction: 'Roast chickpeas on separate pan for last 15 minutes.', timer: 15 },
      { step: 5, instruction: 'Whisk tahini, lemon juice, maple syrup, and water for dressing.' },
      { step: 6, instruction: 'Assemble bowls with quinoa, vegetables, chickpeas, and dressing.' }
    ],
    nutrition: { calories: 420, protein: 16, carbs: 58, fat: 16, fiber: 12, sugar: 12, sodium: 280 },
    tags: ['healthy', 'vegan', 'meal-prep'],
    dietary: ['vegan', 'gluten-free', 'dairy-free'],
    ratings: { average: 4.4, count: 41 },
    cookCount: 8,
    lastCookedDays: 7,
    createdDays: 18
  },

  {
    id: 'demo-recipe-12',
    title: 'Greek Chicken Bowls',
    description: 'Mediterranean-inspired bowls with marinated chicken and fresh vegetables.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    difficulty: 'medium',
    cuisine: 'greek',
    mealType: ['lunch', 'dinner'],
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    restTime: 30,
    servings: 4,
    servingsNotes: 'Serves 4 people',
    ingredients: [
      { name: 'Chicken Thighs', amount: 2, unit: 'lbs', notes: 'boneless', category: 'protein' },
      { name: 'Greek Yogurt', amount: 1, unit: 'cup', category: 'dairy' },
      { name: 'Cucumber', amount: 2, unit: 'pieces', notes: 'diced', category: 'vegetables' },
      { name: 'Cherry Tomatoes', amount: 2, unit: 'cups', notes: 'halved', category: 'vegetables' },
      { name: 'Red Onion', amount: 0.5, unit: 'piece', notes: 'sliced', category: 'vegetables' },
      { name: 'Feta Cheese', amount: 1, unit: 'cup', notes: 'crumbled', category: 'dairy' },
      { name: 'Oregano', amount: 2, unit: 'tsp', notes: 'dried', category: 'spices' },
      { name: 'Olive Oil', amount: 0.25, unit: 'cup', category: 'oils' },
      { name: 'Lemon', amount: 2, unit: 'pieces', notes: 'juiced', category: 'fruits' }
    ],
    instructions: [
      { step: 1, instruction: 'Marinate chicken with half the olive oil, lemon juice, oregano for 30 minutes.' },
      { step: 2, instruction: 'Grill or pan-sear chicken until cooked through, 6-8 minutes per side.', timer: 16 },
      { step: 3, instruction: 'Let chicken rest 5 minutes, then slice.', timer: 5 },
      { step: 4, instruction: 'Make tzatziki: mix yogurt, diced cucumber, garlic, lemon juice.' },
      { step: 5, instruction: 'Combine tomatoes, red onion, remaining olive oil and lemon.' },
      { step: 6, instruction: 'Assemble bowls with chicken, vegetables, feta, and tzatziki.' }
    ],
    nutrition: { calories: 485, protein: 42, carbs: 12, fat: 30, fiber: 3, sugar: 8, sodium: 620 },
    tags: ['mediterranean', 'protein-rich', 'healthy'],
    dietary: ['gluten-free'],
    ratings: { average: 4.6, count: 38 },
    cookCount: 10,
    lastCookedDays: 4,
    createdDays: 12
  },

  // Quick & Easy
  {
    id: 'demo-recipe-13',
    title: 'Caprese Grilled Cheese',
    description: 'Elevated grilled cheese with fresh mozzarella, basil, and tomatoes.',
    image: 'https://images.unsplash.com/photo-1528735602786-227c32fd7bcd?w=400',
    difficulty: 'easy',
    cuisine: 'italian',
    mealType: ['lunch', 'snack'],
    prepTime: 10,
    cookTime: 8,
    totalTime: 18,
    servings: 2,
    servingsNotes: 'Makes 2 sandwiches',
    ingredients: [
      { name: 'Sourdough Bread', amount: 4, unit: 'slices', category: 'grains' },
      { name: 'Fresh Mozzarella', amount: 8, unit: 'oz', notes: 'sliced', category: 'dairy' },
      { name: 'Tomatoes', amount: 2, unit: 'pieces', notes: 'large, sliced', category: 'vegetables' },
      { name: 'Fresh Basil', amount: 0.25, unit: 'cup', notes: 'leaves', category: 'herbs' },
      { name: 'Butter', amount: 3, unit: 'tbsp', notes: 'softened', category: 'dairy' },
      { name: 'Balsamic Glaze', amount: 2, unit: 'tbsp', isOptional: true, category: 'condiments' }
    ],
    instructions: [
      { step: 1, instruction: 'Butter one side of each bread slice.' },
      { step: 2, instruction: 'Layer mozzarella, tomato, and basil on unbuttered sides.' },
      { step: 3, instruction: 'Top with remaining bread, buttered side out.' },
      { step: 4, instruction: 'Cook in skillet over medium heat until golden, 3-4 minutes per side.', timer: 8 },
      { step: 5, instruction: 'Let cool slightly, then slice. Drizzle with balsamic glaze if using.' }
    ],
    nutrition: { calories: 520, protein: 28, carbs: 42, fat: 28, fiber: 3, sugar: 8, sodium: 920 },
    tags: ['quick', 'comfort-food', 'italian'],
    dietary: ['vegetarian'],
    ratings: { average: 4.3, count: 29 },
    cookCount: 14,
    lastCookedDays: 9,
    createdDays: 33
  },

  {
    id: 'demo-recipe-14',
    title: 'Shrimp Scampi',
    description: 'Garlicky shrimp in white wine butter sauce over pasta.',
    image: 'https://images.unsplash.com/photo-1563379091339-03246963d888?w=400',
    difficulty: 'easy',
    cuisine: 'italian',
    mealType: ['dinner'],
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    servings: 4,
    servingsNotes: 'Serves 4 people',
    ingredients: [
      { name: 'Large Shrimp', amount: 1.5, unit: 'lbs', notes: 'peeled and deveined', category: 'protein' },
      { name: 'Linguine', amount: 1, unit: 'lb', category: 'grains' },
      { name: 'Garlic', amount: 6, unit: 'cloves', notes: 'minced', category: 'vegetables' },
      { name: 'White Wine', amount: 0.5, unit: 'cup', notes: 'dry', category: 'liquids' },
      { name: 'Butter', amount: 6, unit: 'tbsp', category: 'dairy' },
      { name: 'Olive Oil', amount: 3, unit: 'tbsp', category: 'oils' },
      { name: 'Lemon', amount: 2, unit: 'pieces', notes: 'juiced', category: 'fruits' },
      { name: 'Parsley', amount: 0.25, unit: 'cup', notes: 'chopped', category: 'herbs' },
      { name: 'Red Pepper Flakes', amount: 0.25, unit: 'tsp', isOptional: true, category: 'spices' }
    ],
    instructions: [
      { step: 1, instruction: 'Cook linguine according to package directions. Reserve 1 cup pasta water.', timer: 8 },
      { step: 2, instruction: 'Season shrimp with salt and pepper.' },
      { step: 3, instruction: 'Heat oil and 2 tbsp butter in large skillet over medium-high heat.' },
      { step: 4, instruction: 'Cook shrimp until pink, about 2 minutes per side. Remove.', timer: 4 },
      { step: 5, instruction: 'Add garlic to pan, cook 30 seconds until fragrant.', timer: 1 },
      { step: 6, instruction: 'Add wine, lemon juice, and red pepper flakes. Simmer 2 minutes.', timer: 2 },
      { step: 7, instruction: 'Toss with pasta, shrimp, remaining butter, and parsley.' }
    ],
    nutrition: { calories: 520, protein: 36, carbs: 48, fat: 18, fiber: 2, sugar: 3, sodium: 480 },
    tags: ['quick', 'elegant', 'italian'],
    dietary: ['pescatarian'],
    ratings: { average: 4.7, count: 52 },
    isFavorite: true,
    cookCount: 18,
    lastCookedDays: 1,
    createdDays: 8
  },

  // Desserts
  {
    id: 'demo-recipe-15',
    title: 'Chocolate Chip Cookies',
    description: 'Classic chewy chocolate chip cookies with crispy edges.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400',
    difficulty: 'easy',
    cuisine: 'american',
    mealType: ['snack', 'dessert'],
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    servings: 24,
    servingsNotes: 'Makes 24 cookies',
    ingredients: [
      { name: 'All-purpose Flour', amount: 2.25, unit: 'cups', category: 'grains' },
      { name: 'Butter', amount: 1, unit: 'cup', notes: 'softened', category: 'dairy' },
      { name: 'Brown Sugar', amount: 0.75, unit: 'cup', notes: 'packed', category: 'sweeteners' },
      { name: 'Granulated Sugar', amount: 0.25, unit: 'cup', category: 'sweeteners' },
      { name: 'Eggs', amount: 2, unit: 'pieces', notes: 'large', category: 'dairy' },
      { name: 'Vanilla Extract', amount: 2, unit: 'tsp', category: 'baking' },
      { name: 'Baking Soda', amount: 1, unit: 'tsp', category: 'baking' },
      { name: 'Salt', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Chocolate Chips', amount: 2, unit: 'cups', category: 'baking' }
    ],
    instructions: [
      { step: 1, instruction: 'Preheat oven to 375°F. Line baking sheets with parchment.', temperature: 375 },
      { step: 2, instruction: 'Cream butter and both sugars until light and fluffy.', timer: 3 },
      { step: 3, instruction: 'Beat in eggs and vanilla until combined.' },
      { step: 4, instruction: 'In separate bowl, whisk flour, baking soda, and salt.' },
      { step: 5, instruction: 'Gradually mix dry ingredients into wet ingredients.' },
      { step: 6, instruction: 'Fold in chocolate chips.' },
      { step: 7, instruction: 'Drop rounded tablespoons onto baking sheets. Bake 9-11 minutes.', timer: 11 }
    ],
    nutrition: { calories: 180, protein: 2, carbs: 26, fat: 8, fiber: 1, sugar: 18, sodium: 140 },
    tags: ['dessert', 'cookies', 'classic'],
    dietary: ['vegetarian'],
    ratings: { average: 4.9, count: 89 },
    isFavorite: true,
    cookCount: 32,
    lastCookedDays: 3,
    createdDays: 5
  },

  // Breakfast/Brunch
  {
    id: 'demo-recipe-16',
    title: 'Overnight French Toast Casserole',
    description: 'Make-ahead French toast casserole perfect for weekend mornings.',
    image: 'https://images.unsplash.com/photo-1481070555726-e2fe8357725c?w=400',
    difficulty: 'easy',
    cuisine: 'american',
    mealType: ['breakfast', 'brunch'],
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    restTime: 480,
    servings: 8,
    servingsNotes: 'Serves 8-10 people',
    ingredients: [
      { name: 'Brioche Bread', amount: 1, unit: 'loaf', notes: 'day-old, cubed', category: 'grains' },
      { name: 'Eggs', amount: 8, unit: 'pieces', notes: 'large', category: 'dairy' },
      { name: 'Milk', amount: 2, unit: 'cups', notes: 'whole milk', category: 'dairy' },
      { name: 'Heavy Cream', amount: 0.5, unit: 'cup', category: 'dairy' },
      { name: 'Vanilla Extract', amount: 2, unit: 'tsp', category: 'baking' },
      { name: 'Cinnamon', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Maple Syrup', amount: 0.25, unit: 'cup', category: 'sweeteners' },
      { name: 'Butter', amount: 4, unit: 'tbsp', notes: 'melted', category: 'dairy' },
      { name: 'Powdered Sugar', amount: 2, unit: 'tbsp', isOptional: true, category: 'sweeteners' }
    ],
    instructions: [
      { step: 1, instruction: 'Grease 9x13 inch baking dish. Arrange bread cubes in dish.' },
      { step: 2, instruction: 'Whisk eggs, milk, cream, vanilla, cinnamon, and maple syrup.' },
      { step: 3, instruction: 'Pour egg mixture over bread. Press down gently to soak.' },
      { step: 4, instruction: 'Cover and refrigerate overnight, at least 8 hours.' },
      { step: 5, instruction: 'Remove from fridge 30 minutes before baking. Preheat oven to 350°F.', temperature: 350 },
      { step: 6, instruction: 'Drizzle with melted butter. Bake 45-50 minutes until golden.', timer: 50 },
      { step: 7, instruction: 'Let rest 5 minutes. Dust with powdered sugar before serving.' }
    ],
    nutrition: { calories: 380, protein: 14, carbs: 42, fat: 18, fiber: 2, sugar: 22, sodium: 420 },
    tags: ['make-ahead', 'brunch', 'crowd-pleaser'],
    dietary: ['vegetarian'],
    ratings: { average: 4.8, count: 45 },
    cookCount: 6,
    lastCookedDays: 16,
    createdDays: 42
  },

  // Soups & Stews
  {
    id: 'demo-recipe-17',
    title: 'Chicken Noodle Soup',
    description: 'Comforting homemade chicken noodle soup with tender vegetables.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    difficulty: 'easy',
    cuisine: 'american',
    mealType: ['lunch', 'dinner'],
    prepTime: 15,
    cookTime: 45,
    totalTime: 60,
    servings: 6,
    servingsNotes: 'Serves 6 people',
    ingredients: [
      { name: 'Chicken Breasts', amount: 1, unit: 'lb', notes: 'boneless', category: 'protein' },
      { name: 'Egg Noodles', amount: 8, unit: 'oz', notes: 'wide', category: 'grains' },
      { name: 'Chicken Broth', amount: 8, unit: 'cups', category: 'liquids' },
      { name: 'Carrots', amount: 3, unit: 'pieces', notes: 'sliced', category: 'vegetables' },
      { name: 'Celery', amount: 3, unit: 'stalks', notes: 'chopped', category: 'vegetables' },
      { name: 'Onion', amount: 1, unit: 'piece', notes: 'diced', category: 'vegetables' },
      { name: 'Garlic', amount: 3, unit: 'cloves', notes: 'minced', category: 'vegetables' },
      { name: 'Bay Leaves', amount: 2, unit: 'pieces', category: 'spices' },
      { name: 'Fresh Thyme', amount: 1, unit: 'tsp', category: 'herbs' }
    ],
    instructions: [
      { step: 1, instruction: 'In large pot, bring broth to boil. Add chicken breasts.', timer: 10 },
      { step: 2, instruction: 'Reduce heat, simmer until chicken is cooked, about 15 minutes.', timer: 15 },
      { step: 3, instruction: 'Remove chicken, shred when cool. Strain and reserve broth.' },
      { step: 4, instruction: 'In same pot, sauté onion, carrots, celery until tender.', timer: 8 },
      { step: 5, instruction: 'Add garlic, cook 1 minute. Return broth to pot.', timer: 1 },
      { step: 6, instruction: 'Add bay leaves, thyme, and noodles. Cook until noodles are tender.', timer: 8 },
      { step: 7, instruction: 'Stir in shredded chicken. Remove bay leaves before serving.' }
    ],
    nutrition: { calories: 280, protein: 22, carbs: 28, fat: 8, fiber: 3, sugar: 4, sodium: 980 },
    tags: ['comfort-food', 'soup', 'healing'],
    dietary: ['dairy-free'],
    ratings: { average: 4.6, count: 78 },
    cookCount: 13,
    lastCookedDays: 19,
    createdDays: 50
  },

  {
    id: 'demo-recipe-18',
    title: 'Vegetarian Chili',
    description: 'Hearty three-bean chili packed with vegetables and spices.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    difficulty: 'easy',
    cuisine: 'american',
    mealType: ['lunch', 'dinner'],
    prepTime: 15,
    cookTime: 40,
    totalTime: 55,
    servings: 8,
    servingsNotes: 'Serves 8 people',
    ingredients: [
      { name: 'Black Beans', amount: 1, unit: 'can', notes: 'drained and rinsed', category: 'protein' },
      { name: 'Kidney Beans', amount: 1, unit: 'can', notes: 'drained and rinsed', category: 'protein' },
      { name: 'Pinto Beans', amount: 1, unit: 'can', notes: 'drained and rinsed', category: 'protein' },
      { name: 'Crushed Tomatoes', amount: 1, unit: 'can', notes: '28 oz', category: 'vegetables' },
      { name: 'Bell Peppers', amount: 2, unit: 'pieces', notes: 'diced', category: 'vegetables' },
      { name: 'Onion', amount: 1, unit: 'piece', notes: 'diced', category: 'vegetables' },
      { name: 'Chili Powder', amount: 2, unit: 'tbsp', category: 'spices' },
      { name: 'Cumin', amount: 1, unit: 'tbsp', category: 'spices' },
      { name: 'Smoked Paprika', amount: 1, unit: 'tsp', category: 'spices' }
    ],
    instructions: [
      { step: 1, instruction: 'Heat oil in large pot. Sauté onion and peppers until soft.', timer: 8 },
      { step: 2, instruction: 'Add garlic, chili powder, cumin, paprika. Cook 1 minute.', timer: 1 },
      { step: 3, instruction: 'Add crushed tomatoes, all beans, and 2 cups water.' },
      { step: 4, instruction: 'Bring to boil, then reduce heat and simmer 30 minutes.', timer: 30 },
      { step: 5, instruction: 'Season with salt and pepper. Serve with toppings.' }
    ],
    nutrition: { calories: 240, protein: 14, carbs: 44, fat: 2, fiber: 16, sugar: 8, sodium: 580 },
    tags: ['vegetarian', 'high-fiber', 'meal-prep'],
    dietary: ['vegetarian', 'vegan', 'gluten-free'],
    ratings: { average: 4.4, count: 63 },
    cookCount: 9,
    lastCookedDays: 13,
    createdDays: 38
  },

  // International Cuisine
  {
    id: 'demo-recipe-19',
    title: 'Pad Thai',
    description: 'Authentic Thai stir-fried noodles with tamarind sauce and peanuts.',
    image: 'https://images.unsplash.com/photo-1559314809-0f31657def5e?w=400',
    difficulty: 'medium',
    cuisine: 'thai',
    mealType: ['lunch', 'dinner'],
    prepTime: 25,
    cookTime: 15,
    totalTime: 40,
    servings: 4,
    servingsNotes: 'Serves 4 people',
    ingredients: [
      { name: 'Rice Noodles', amount: 8, unit: 'oz', notes: 'pad thai style', category: 'grains' },
      { name: 'Shrimp', amount: 1, unit: 'lb', notes: 'peeled', category: 'protein' },
      { name: 'Eggs', amount: 3, unit: 'pieces', category: 'dairy' },
      { name: 'Bean Sprouts', amount: 2, unit: 'cups', category: 'vegetables' },
      { name: 'Tamarind Paste', amount: 3, unit: 'tbsp', category: 'condiments' },
      { name: 'Fish Sauce', amount: 3, unit: 'tbsp', category: 'condiments' },
      { name: 'Brown Sugar', amount: 2, unit: 'tbsp', category: 'sweeteners' },
      { name: 'Peanuts', amount: 0.5, unit: 'cup', notes: 'crushed', category: 'nuts' },
      { name: 'Lime', amount: 2, unit: 'pieces', notes: 'cut in wedges', category: 'fruits' }
    ],
    instructions: [
      { step: 1, instruction: 'Soak rice noodles in warm water until soft, about 30 minutes.' },
      { step: 2, instruction: 'Mix tamarind paste, fish sauce, and brown sugar for sauce.' },
      { step: 3, instruction: 'Heat oil in wok over high heat. Cook shrimp until pink.', timer: 3 },
      { step: 4, instruction: 'Push shrimp to one side, scramble eggs on other side.', timer: 2 },
      { step: 5, instruction: 'Add drained noodles and sauce. Toss until coated.', timer: 3 },
      { step: 6, instruction: 'Add bean sprouts, cook 1 minute. Garnish with peanuts and lime.', timer: 1 }
    ],
    nutrition: { calories: 420, protein: 28, carbs: 52, fat: 12, fiber: 3, sugar: 8, sodium: 1240 },
    tags: ['thai', 'stir-fry', 'authentic'],
    dietary: ['pescatarian', 'gluten-free'],
    ratings: { average: 4.5, count: 34 },
    cookCount: 5,
    lastCookedDays: 21,
    createdDays: 47
  },

  // Pizza & Pasta
  {
    id: 'demo-recipe-20',
    title: 'Margherita Pizza',
    description: 'Classic Neapolitan pizza with fresh mozzarella, basil, and tomatoes.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    difficulty: 'medium',
    cuisine: 'italian',
    mealType: ['lunch', 'dinner'],
    prepTime: 120,
    cookTime: 12,
    totalTime: 132,
    restTime: 120,
    servings: 4,
    servingsNotes: 'Makes 2 personal pizzas',
    ingredients: [
      { name: 'Pizza Dough', amount: 1, unit: 'lb', notes: 'homemade or store-bought', category: 'grains' },
      { name: 'San Marzano Tomatoes', amount: 1, unit: 'can', notes: '14 oz, crushed', category: 'vegetables' },
      { name: 'Fresh Mozzarella', amount: 8, unit: 'oz', notes: 'torn into pieces', category: 'dairy' },
      { name: 'Fresh Basil', amount: 0.25, unit: 'cup', notes: 'leaves', category: 'herbs' },
      { name: 'Olive Oil', amount: 3, unit: 'tbsp', notes: 'extra virgin', category: 'oils' },
      { name: 'Garlic', amount: 2, unit: 'cloves', notes: 'minced', category: 'vegetables' },
      { name: 'Sea Salt', amount: 1, unit: 'tsp', category: 'spices' },
      { name: 'Parmesan Cheese', amount: 0.25, unit: 'cup', notes: 'grated', isOptional: true, category: 'dairy' }
    ],
    instructions: [
      { step: 1, instruction: 'Let pizza dough come to room temperature for 2 hours.' },
      { step: 2, instruction: 'Preheat oven to 500°F with pizza stone if available.', temperature: 500 },
      { step: 3, instruction: 'Mix crushed tomatoes with garlic, salt, and 1 tbsp olive oil.' },
      { step: 4, instruction: 'Stretch dough into 2 circles on floured surface.' },
      { step: 5, instruction: 'Spread thin layer of sauce on each pizza, leaving border.' },
      { step: 6, instruction: 'Add mozzarella pieces and drizzle with remaining olive oil.' },
      { step: 7, instruction: 'Bake 10-12 minutes until crust is golden. Top with fresh basil.', timer: 12 }
    ],
    nutrition: { calories: 520, protein: 24, carbs: 58, fat: 22, fiber: 3, sugar: 6, sodium: 980 },
    tags: ['pizza', 'italian', 'classic'],
    dietary: ['vegetarian'],
    ratings: { average: 4.7, count: 91 },
    isFavorite: true,
    cookCount: 16,
    lastCookedDays: 5,
    createdDays: 14
  }
];